# Generated by Django 5.0.4 on 2024-04-24 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Algebra', 'Algebra'), ('Calculus', 'Calculus'), ('Differential Calculus', 'Differential Calculus'), ('Geometry', 'Geometry'), ('Additional', 'Additional'), ('Word Problems', 'Word Problems')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation_history', models.TextField(blank=True)),
                ('ai_generated_content', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
