# Generated by Django 5.0.4 on 2024-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathai', '0002_alter_mathtopic_conversation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtopic',
            name='conversation_history',
            field=models.TextField(default='[]'),
        ),
    ]
