# Generated by Django 5.0.4 on 2024-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathai', '0003_alter_mathtopic_conversation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtopic',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
